# SonarQube Project Configuration
sonar.projectKey=Devops-demo-project
sonar.projectName=Devops-demo-project
sonar.projectVersion=1.0

# Source & Test paths
sonar.sources=.
sonar.inclusions=backend/**,admin/src/**,frontend/src/**,chat/**
sonar.exclusions=**/node_modules/**,**/.git/**,**/dist/**,**/build/**,**/coverage/**,**/logs/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,**/tests/**,**/__tests__/**

sonar.tests=.
sonar.test.inclusions=backend/tests/**,admin/src/__tests__/**,frontend/src/__tests__/**,chat/server/tests/**,chat/client/src/__tests__/**

# Coverage & Encoding
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.sourceEncoding=UTF-8